version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "7007:7007"
    environment:
      - REDIS_URL=redis://redis:6379  # This should work with Docker's internal DNS
    depends_on:
      - redis  # Ensures Redis starts before the backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
